# 3.3 重构代码-自定义验证对象

我们之前写的代码，有一些细节问题。

### 1.传入错误的参数，虽然没有添加到数据库，但是返回 结果显示正常

这是因为，form.validate()如果校验不通过，他不会抛出异常，而是会将异常信息存储在form对象中。
所以这个时候我们应该判断如果校验不通过，就抛出一个自定义的异常。


werkzeug为我们提供的大量的异常，都继承自HTTPException，但是这些异常都很具体，不能为我们所用。不过我们可以自己定义一个异常来继承HTTPException


### 2.自定义异常

rest中状态码代表的意义
- 400 参数错误
- 401 未授权
- 403 禁止访问
- 404 没有找到资源或者页面
- 500 服务器未知错误
- 200 查询成功
- 201 更新/创建成功
- 204 删除成功
- 301/302 重定向